### ISSUE TITLE
manifest

### ISSUE THREAD

**Issue by hhboltz** [kuersten/aappp#1]
Hi,

I am not overly familiar with the setup process in python, but for me installation as is does not work. Posting the contents of a MANIFEST.in that does work

include README.txt
include LICENSE.txt
graft src

The two issues seem to be that the directory pattern does not like the leading "/" and all lines should have a command (here include). Also: since src is grafted including the files per hand felt unneccessary. Again, I don't know these things, so it might be a version issue.

Also two warnings remain: 
warning: check: missing required meta-data: url

warning: check: missing meta-data: either (author and author_email) or (maintainer and maintainer_email) must be supplied
these should be stated in the setup.py, I guess

**Comment by kuersten** [comment]
Hi,
thank you for the feedback, I updated the metadata and changed MANIFEST.in
hope it works now.
